---
# tasks file for mariadb
- name: installation de notre Mariadb
  yum:
   name: "{{ item }}"
   state: present
  loop:
    - mariadb
    - python2-PyMySQL
    - mariadb-server

- name: Activationde notre Mariadb
  systemd:
   name: mariadb
   state: started
   enabled: yes
